{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyNdoFx0gHf/Ke8Svi+YkZ5t",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/iamiratsh/amir-hossein-atashkar/blob/main/METHOD%20WITHOUT%20IS.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "#METOD WITHOUT IS\n",
        "#Amir Atashkar\n",
        "\n",
        "#capitalize #اولین کرکتر رشته را بزرگ میکند\n",
        "#txt = 'hello hello'\n",
        "#txt.capitalize()\n",
        "# HELLO hello\n",
        "\n",
        "#-----------------------------------------------------------------\n",
        "\n",
        "#center #طول رشته را زیاد کرده و آن را در وسط قرار میدهد\n",
        "#txt = \"hello\"\n",
        "#txt.center(11)\n",
        "#    hello\n",
        "#txt = \"hello\"\n",
        "#txt.center(11 , '<')\n",
        "# <<<hello<<<\n",
        "\n",
        "#------------------------------------------------------------------\n",
        "\n",
        "#count #تعداد دفعاتی که یک مقدار در یک رشته تکرار شده است را برمیگرداند\n",
        "#txt = \"afhelloagaghellogmbaghelloqrqt\"\n",
        "#txt.count(\"hello\")\n",
        "# 3\n",
        "\n",
        "#-------------------------------------------------------------------\n",
        "\n",
        "#endswith #چک میکند که آیا یک رشته با کاراکتر خاصی تمام میشود یا خیر\n",
        "#txt = \"Hello\"\n",
        "#txt.endswith(\"o\")\n",
        "# True\n",
        "\n",
        "#--------------------------------------------------------------------\n",
        "\n",
        "#find #چک میکند که آیا یک مقدار در یک رشته وجود دارد یا خیر\n",
        "#txt = \"afmdaofmhellosvm\"\n",
        "#txt.find(\"hello\")\n",
        "# 8\n",
        "\n",
        "#---------------------------------------------------------------------\n",
        "\n",
        "#lower #یک رشته را به حروف کوچک تبدیل میکند\n",
        "#txt = \"Hello\"\n",
        "#txt.lower()\n",
        "# hello\n",
        "#----------------------------------------------------------------------\n",
        "\n",
        "#format #یک متغیر را در یک رشته جایگذاری میکند\n",
        "#txt = \"hello my name is {sara}\"\n",
        "#txt.format(sara = \"rozhan\")\n",
        "#hello my name is rozhan\n",
        "\n",
        "#----------------------------------------------------------------------\n",
        "\n",
        "#index #چک میکند که آیا یک مقدار در یک رشته وجود دارد یه خیر\n",
        "#اگر وجود داشته باشد ایندکس آنرا برمیگرداند اگرنه ارور خواهد داد\n",
        "\n",
        "#txt = \"afmdaofmhellosvm\"\n",
        "#txt.index(\"hello\")\n",
        "# 8\n",
        "\n",
        "\n",
        "#txt = \"afmdaofmsvm\"\n",
        "#txt.find(\"hello\")\n",
        "# -1\n",
        "\n",
        "#------------------------------------------------------------------------\n",
        "\n",
        "#replace # یک مقدار را با یک مقدار دیگر جایگزین میکند\n",
        "#txt = \"hello\"\n",
        "#txt.replace(\"hello\", \"bye\")\n",
        "# bye\n",
        "\n",
        "#-------------------------------------------------------------------------\n",
        "\n",
        "#startswith #چک میکند که آیا یک رشته با کاراکتر خاصی شروع میشود یا خیر\n",
        "#txt = \"Hello, bye\"\n",
        "#txt.startswith(\"Hello\")\n",
        "# True\n",
        "\n",
        "#--------------------------------------------------------------------------\n",
        "\n",
        "#strip #فاصله‌های خالی را از یک رشته حذف میکند\n",
        "#txt = \"     hello     \"\n",
        "#txt.strip()\n",
        "# hello\n",
        "\n",
        "#---------------------------------------------------------------------------\n",
        "\n",
        "#swapcase #کاراکترهای کوچک را به بزرگ و کاراکترهای بزرگ را به کوچک تبدیل میکند\n",
        "#txt = \"HEllo\"\n",
        "#txt.swapcase()\n",
        "# heLLO\n",
        "\n",
        "#-----------------------------------------------------------------------------\n",
        "\n",
        "#upper #تبدیل کاراکترهای کوچک به بزرگ\n",
        "#txt = \"hello\"\n",
        "#txt.upper()\n",
        "# HELLO"
      ],
      "metadata": {
        "id": "tIu_TS-hYTA4"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}